version: '3.8'

services:
  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - streamlit
    restart: always

  streamlit:
    build: .
    command: streamlit run app_streamlit.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    restart: always
